spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pair?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.pair.pojo
  mapper-locations: classpath*:com/pair/mapper/*.xml



