#端口号配置
server:
  port: 8080

spring:
  #模板引擎配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    # 禁用缓存 ---改动html即时刷新
    cache: false
    servlet:
      content-type: text/html
#  #。。。。
#  devtools:
#    restart:
#      # 热部署开关
#      enabled: true

  #静态文件配置
  resources:
    static-locations: classpath:/static,classpath:/META-INF/resources,classpath:/templates/
  #jdbc配置   （1.15.141.65 : 3306）
  datasource:
    url: jdbc:mysql://1.15.141.65:3306/pairproject?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Etc/GMT-8
    username: root
    password: Root123.
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  #映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #模型所在的保命
  type-aliases-package: com.practice.pair.pairproject.pojo
