spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paper?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: "001221"
    driver-class-name: com.mysql.jdbc.Driver

#配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
