spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pair?useSSL=false&useUnicode=true&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.jia.pojo
  mapper-locations: classpath*:com/pair/mapper/*.xml